### ISSUE TITLE
Constructors name change required.

### ISSUE THREAD

**Issue by dobaniashish** [sparc/phpWhois.org#1]
Hello,

I am getting the following error:

`Methods with the same name as their class will not be constructors in a future version of PHP; classname has a deprecated constructor`

Caused because of deprecation of PHP 4 style constructors.

More Information:

> PHP 4 style constructors (methods that have the same name as the class they are defined in) are deprecated, and will be removed in the future. PHP 7 will emit E_DEPRECATED if a PHP 4 constructor is the only constructor defined within a class. Classes that implement a __construct() method are unaffected. 
From: http://php.net/manual/en/migration70.deprecated.php

PHP Version: 7.0.22

**Comment by sparc** [comment]
Please post the full error, including file name and line number

**Comment by dobaniashish** [comment]
There are multiple files that require this change.

In total there were 3 Error for Constructors name change required and 1 error for "Illegal string offset 'handler'".

Here's the full error code:
https://pastebin.com/8mQu6yAL

Screenshot:
![screen shot 2018-05-17 at 16 51 24](https://user-images.githubusercontent.com/20734580/40174450-c7a6ebec-59f2-11e8-814a-e162537fb73f.png)

Html Code for error:
https://pastebin.com/C8D3S2dT

Tell me if you require more information.

**Comment by sparc** [comment]
Fixed
