### ISSUE TITLE
[Bug] ICANN GTLD 'Deep WHOIS' is broken

### ISSUE THREAD

**Issue by texh** [sparc/phpWhois.org#3]
Heya,

I noticed 'deep whois' or recursive lookups aren't working out of the box.

Looking at `$REG_FIELDS[]` in `src/whois.gtld.php` which looks like it's used to map the raw WHOIS data to some useable data structure internally. From what I can tell the `'Whois Server:'` key should probably be updated to `'Registrar WHOIS Server:'`, unless some method exists for it to match either of the two.

The WHOIS response format changes are mentioned at the following links:
https://www.icann.org/resources/pages/approved-with-specs-2013-09-17-en#whois
https://www.centralnic.com/company/news/2016/changes-to-whois
Or by just querying a bunch of .com/.net domains

**Comment by kotuk** [comment]
$whois->deep_whois = true;
is not working

**Comment by kotuk** [comment]
any, com, tv, net, eu

**Comment by kotuk** [comment]
bugfix helped, thank you

**Comment by texh** [comment]
Not sure it will work for EU, but appears to work for the other 3 :)
